import type { Product, Category, Vendor, Warehouse, User, Department, OutwardTransaction, PurchaseInvoice, VendorPayment, DailySale, BanquetSale, TaxRate, AdditionalCharge, BillingPreferences } from './types';
import { UserRole, PaymentMode } from './types';

export const USERS: User[] = [
  { id: 1, name: 'Admin User', role: UserRole.ADMIN },
  { id: 2, name: 'Manager User', role: UserRole.MANAGER },
  { id: 3, name: 'Staff User', role: UserRole.STAFF },
];

export const CATEGORIES: Category[] = [
  { id: 1, name: 'Beverages' },
  { id: 2, name: 'Dairy' },
  { id: 3, name: 'Bakery' },
  { id: 4, name: 'Groceries' },
  { id: 5, name: 'Spices' },
  { id: 6, name: 'Housekeeping' },
  { id: 7, name: 'Vegetables' },
  { id: 8, name: 'Seafood' },
  { id: 9, name: 'Non Veg' },
  { id: 10, name: 'Fuel & Utilities' },
];

export const VENDORS: Vendor[] = [
  { id: 1, name: 'Default Vendor', email: 'info@vendor.com', phone: '000-000-0000', address: 'Market Yard', gstin: '27AAAAA0000A1Z5' },
  { id: 2, name: 'Global Foods Inc.', email: 'john@globalfoods.com', phone: '123-456-7890', address: '123 Global Way', gstin: '27BBBBB1111B2Z6' },
];

export const WAREHOUSES: Warehouse[] = [
  { id: 1, name: 'Main Store', location: 'Basement' },
];

export const DEPARTMENTS: Department[] = [
  { id: 1, name: 'Kitchen' },
  { id: 2, name: 'Bar' },
  { id: 3, name: 'Housekeeping' },
];

export const PRODUCTS: Product[] = [
  { id: 1, name: 'ATTA', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 38.0, gstRate: 5, quantity: 270.0, initialQuantity: 270.0, reorderLevel: 50 },
  { id: 2, name: 'MAIDA', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 39.0, gstRate: 5, quantity: 150.0, initialQuantity: 150.0, reorderLevel: 30 },
  { id: 3, name: 'CORN FLOUR', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 42.9, gstRate: 5, quantity: 25.0, initialQuantity: 25.0, reorderLevel: 5 },
  { id: 4, name: 'BESAN', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 98.0, gstRate: 5, quantity: 18.0, initialQuantity: 18.0, reorderLevel: 5 },
  { id: 5, name: 'RAWA', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 42.0, gstRate: 5, quantity: 4.0, initialQuantity: 4.0, reorderLevel: 10 },
  { id: 6, name: 'BASMATI RICE', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 120.0, gstRate: 5, quantity: 90.0, initialQuantity: 90.0, reorderLevel: 25 },
  { id: 7, name: 'HEAVEN HARVEST', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 115.0, gstRate: 5, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 10 },
  { id: 8, name: 'SHELLA RICE', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 94.0, gstRate: 5, quantity: 30.0, initialQuantity: 30.0, reorderLevel: 10 },
  { id: 9, name: 'STAFF RICE', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 32.0, gstRate: 5, quantity: 150.0, initialQuantity: 150.0, reorderLevel: 50 },
  { id: 10, name: 'TOOR DAL', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 111.0, gstRate: 5, quantity: 21.0, initialQuantity: 21.0, reorderLevel: 10 },
  { id: 11, name: 'CHAWALI DAL', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 0.0, gstRate: 5, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 5 },
  { id: 12, name: 'WHOLE BLACK CHANA', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 76.0, gstRate: 5, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 5 },
  { id: 13, name: 'CHANA DAL', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 98.0, gstRate: 5, quantity: 3.0, initialQuantity: 3.0, reorderLevel: 10 },
  { id: 14, name: 'WHOLE MASUR', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 0.0, gstRate: 5, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 5 },
  { id: 15, name: 'MASOOR DAL', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 80.0, gstRate: 5, quantity: 52.0, initialQuantity: 52.0, reorderLevel: 10 },
  { id: 16, name: 'KABULI CHANA', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 145.0, gstRate: 5, quantity: 5.0, initialQuantity: 5.0, reorderLevel: 5 },
  { id: 17, name: 'WHITE WATANA', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 90.0, gstRate: 5, quantity: 10.0, initialQuantity: 10.0, reorderLevel: 5 },
  { id: 18, name: 'ROASTED CHANA DAL', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 95.0, gstRate: 5, quantity: 0.3, initialQuantity: 0.3, reorderLevel: 2 },
  { id: 19, name: 'BLACK DAL', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 120.0, gstRate: 5, quantity: 10.0, initialQuantity: 10.0, reorderLevel: 5 },
  { id: 20, name: 'URAD DAL', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 130.0, gstRate: 5, quantity: 32.0, initialQuantity: 32.0, reorderLevel: 10 },
  { id: 21, name: 'WHOLE DHANIYA', unit: 'kg', categoryId: 5, vendorId: 1, warehouseId: 1, purchasePrice: 142.9, gstRate: 5, quantity: 1.9, initialQuantity: 1.9, reorderLevel: 2 },
  { id: 22, name: 'MOOG DAL', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 110.0, gstRate: 5, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 5 },
  { id: 23, name: 'GREEEN WATANA', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 76.0, gstRate: 5, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 5 },
  { id: 24, name: 'SOYABEEN', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 89.0, gstRate: 5, quantity: 5.0, initialQuantity: 5.0, reorderLevel: 5 },
  { id: 25, name: 'MATAKI', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 105.0, gstRate: 5, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 5 },
  { id: 26, name: 'RAJMA', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 105.0, gstRate: 5, quantity: 3.8, initialQuantity: 3.8, reorderLevel: 5 },
  { id: 27, name: 'PEANUT', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 114.0, gstRate: 5, quantity: 2.5, initialQuantity: 2.5, reorderLevel: 5 },
  { id: 28, name: 'ROSTED PEANUTS', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 169.6, gstRate: 5, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 2 },
  { id: 29, name: 'SABUDANA', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 57.5, gstRate: 5, quantity: 15.0, initialQuantity: 15.0, reorderLevel: 5 },
  { id: 30, name: 'POHA', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 55.0, gstRate: 5, quantity: 20.0, initialQuantity: 20.0, reorderLevel: 5 },
  { id: 31, name: 'YEAST', unit: 'kg', categoryId: 3, vendorId: 1, warehouseId: 1, purchasePrice: 227.7, gstRate: 12, quantity: 4.0, initialQuantity: 4.0, reorderLevel: 1 },
  { id: 32, name: 'KAJU', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 850.0, gstRate: 5, quantity: 14.0, initialQuantity: 14.0, reorderLevel: 2 },
  { id: 33, name: 'KAJU TUKADA', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 760.0, gstRate: 5, quantity: 23.0, initialQuantity: 23.0, reorderLevel: 2 },
  { id: 34, name: 'KAJU KANI', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 560.0, gstRate: 5, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 2 },
  { id: 35, name: 'MAGAJ', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 595.0, gstRate: 5, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 2 },
  { id: 36, name: 'KISMIS', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 304.0, gstRate: 5, quantity: 1.0, initialQuantity: 1.0, reorderLevel: 1 },
  { id: 37, name: 'KESAR', unit: 'gm', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 190.5, gstRate: 5, quantity: 1.0, initialQuantity: 1.0, reorderLevel: 0.5 },
  { id: 38, name: 'SUGAR', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 41.0, gstRate: 5, quantity: 150.0, initialQuantity: 150.0, reorderLevel: 50 },
  { id: 39, name: 'GUD', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 50.0, gstRate: 5, quantity: 1.0, initialQuantity: 1.0, reorderLevel: 2 },
  { id: 40, name: 'EMLI', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 130.0, gstRate: 5, quantity: 3.0, initialQuantity: 3.0, reorderLevel: 5 },
  { id: 41, name: 'TATA SALT', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 28.0, gstRate: 0, quantity: 25.0, initialQuantity: 25.0, reorderLevel: 10 },
  { id: 42, name: 'BLACK SALT', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 26.0, gstRate: 0, quantity: 2.0, initialQuantity: 2.0, reorderLevel: 1 },
  { id: 43, name: 'AJINOMOTO', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 152.5, gstRate: 12, quantity: 2.0, initialQuantity: 2.0, reorderLevel: 1 },
  { id: 44, name: 'WHOLE KASHMIRI MIRCH', unit: 'kg', categoryId: 5, vendorId: 1, warehouseId: 1, purchasePrice: 400.0, gstRate: 5, quantity: 12.0, initialQuantity: 12.0, reorderLevel: 2 },
  { id: 45, name: 'TEJ PATTA', unit: 'kg', categoryId: 5, vendorId: 1, warehouseId: 1, purchasePrice: 85.7, gstRate: 5, quantity: 0.2, initialQuantity: 0.2, reorderLevel: 0.5 },
  { id: 46, name: 'BLACK ELAICHI', unit: 'kg', categoryId: 5, vendorId: 1, warehouseId: 1, purchasePrice: 2000.0, gstRate: 5, quantity: 1.0, initialQuantity: 1.0, reorderLevel: 0.2 },
  { id: 47, name: 'GREEN ELAICHI', unit: 'kg', categoryId: 5, vendorId: 1, warehouseId: 1, purchasePrice: 3142.9, gstRate: 5, quantity: 0.5, initialQuantity: 0.5, reorderLevel: 0.1 },
  { id: 48, name: 'WHOLE STAR FOOL', unit: 'kg', categoryId: 5, vendorId: 1, warehouseId: 1, purchasePrice: 666.7, gstRate: 5, quantity: 0.6, initialQuantity: 0.6, reorderLevel: 0.2 },
  { id: 49, name: 'WHOLE DALCHINI', unit: 'kg', categoryId: 5, vendorId: 1, warehouseId: 1, purchasePrice: 304.0, gstRate: 5, quantity: 0.8, initialQuantity: 0.8, reorderLevel: 0.2 },
  { id: 50, name: 'WHOLE BLACK PEPER', unit: 'kg', categoryId: 5, vendorId: 1, warehouseId: 1, purchasePrice: 857.0, gstRate: 5, quantity: 2.5, initialQuantity: 2.5, reorderLevel: 0.5 },
  { id: 51, name: 'WHOLE BORE MIRCHI', unit: 'kg', categoryId: 5, vendorId: 1, warehouseId: 1, purchasePrice: 619.1, gstRate: 5, quantity: 1.5, initialQuantity: 1.5, reorderLevel: 0.5 },
  { id: 52, name: 'WHOLE JEERA', unit: 'kg', categoryId: 5, vendorId: 1, warehouseId: 1, purchasePrice: 381.0, gstRate: 5, quantity: 5.0, initialQuantity: 5.0, reorderLevel: 1 },
  { id: 53, name: 'WHOLE JAVETRI', unit: 'kg', categoryId: 5, vendorId: 1, warehouseId: 1, purchasePrice: 2190.5, gstRate: 5, quantity: 0.4, initialQuantity: 0.4, reorderLevel: 0.1 },
  { id: 54, name: 'WHOLE JAIFAL', unit: 'kg', categoryId: 5, vendorId: 1, warehouseId: 1, purchasePrice: 857.1, gstRate: 5, quantity: 0.5, initialQuantity: 0.5, reorderLevel: 0.1 },
  { id: 55, name: 'WHOLE LAVANG', unit: 'kg', categoryId: 5, vendorId: 1, warehouseId: 1, purchasePrice: 1000.0, gstRate: 5, quantity: 0.5, initialQuantity: 0.5, reorderLevel: 0.1 },
  { id: 56, name: 'WHOLE AJWINE', unit: 'kg', categoryId: 5, vendorId: 1, warehouseId: 1, purchasePrice: 304.0, gstRate: 5, quantity: 2.0, initialQuantity: 2.0, reorderLevel: 0.5 },
  { id: 57, name: 'ROSE MERRY', unit: 'kg', categoryId: 5, vendorId: 1, warehouseId: 1, purchasePrice: 333.0, gstRate: 12, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 0.1 },
  { id: 58, name: 'RAI', unit: 'kg', categoryId: 5, vendorId: 1, warehouseId: 1, purchasePrice: 85.7, gstRate: 5, quantity: 2.0, initialQuantity: 2.0, reorderLevel: 1 },
  { id: 59, name: 'DRY COCONUT', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 342.0, gstRate: 5, quantity: 4.0, initialQuantity: 4.0, reorderLevel: 2 },
  { id: 60, name: 'BADI SAUNF', unit: 'kg', categoryId: 5, vendorId: 1, warehouseId: 1, purchasePrice: 236.0, gstRate: 5, quantity: 8.0, initialQuantity: 8.0, reorderLevel: 2 },
  { id: 61, name: 'MINT SAUNF', unit: 'kg', categoryId: 5, vendorId: 1, warehouseId: 1, purchasePrice: 80.9, gstRate: 5, quantity: 5.0, initialQuantity: 5.0, reorderLevel: 1 },
  { id: 62, name: 'KASTURI METHI', unit: 'kg', categoryId: 5, vendorId: 1, warehouseId: 1, purchasePrice: 304.0, gstRate: 5, quantity: 2.0, initialQuantity: 2.0, reorderLevel: 1 },
  { id: 63, name: 'WHITE TIL', unit: 'kg', categoryId: 5, vendorId: 1, warehouseId: 1, purchasePrice: 190.0, gstRate: 5, quantity: 1.0, initialQuantity: 1.0, reorderLevel: 0.5 },
  { id: 64, name: 'METHI SEED', unit: 'kg', categoryId: 5, vendorId: 1, warehouseId: 1, purchasePrice: 85.0, gstRate: 5, quantity: 0.5, initialQuantity: 0.5, reorderLevel: 0.2 },
  { id: 65, name: 'RED CHILLY POWDER', unit: 'kg', categoryId: 5, vendorId: 1, warehouseId: 1, purchasePrice: 457.1, gstRate: 5, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 5 },
  { id: 66, name: 'DHANIYA POWDER', unit: 'kg', categoryId: 5, vendorId: 1, warehouseId: 1, purchasePrice: 285.7, gstRate: 5, quantity: 3.5, initialQuantity: 3.5, reorderLevel: 5 },
  { id: 67, name: 'JEERA POWDER', unit: 'kg', categoryId: 5, vendorId: 1, warehouseId: 1, purchasePrice: 333.3, gstRate: 5, quantity: 6.0, initialQuantity: 6.0, reorderLevel: 2 },
  { id: 68, name: 'HALDI POWDER', unit: 'kg', categoryId: 5, vendorId: 1, warehouseId: 1, purchasePrice: 309.0, gstRate: 5, quantity: 7.0, initialQuantity: 7.0, reorderLevel: 2 },
  { id: 69, name: 'CHICKEN MASALA 500GM', unit: 'Pkt', categoryId: 5, vendorId: 1, warehouseId: 1, purchasePrice: 722.0, gstRate: 5, quantity: 1.0, initialQuantity: 1.0, reorderLevel: 2 },
  { id: 70, name: 'RED CURRY PASTE', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 411.0, gstRate: 12, quantity: 1.0, initialQuantity: 1.0, reorderLevel: 1 },
  { id: 71, name: 'GARAM MASALA 200GM', unit: 'Pkt', categoryId: 5, vendorId: 1, warehouseId: 1, purchasePrice: 523.8, gstRate: 5, quantity: 2.0, initialQuantity: 2.0, reorderLevel: 5 },
  { id: 72, name: 'SAMBHAR MASALA', unit: 'kg', categoryId: 5, vendorId: 1, warehouseId: 1, purchasePrice: 690.5, gstRate: 5, quantity: 0.8, initialQuantity: 0.8, reorderLevel: 1 },
  { id: 73, name: 'PAV BHAJI MASALA 500GR', unit: 'Pkt', categoryId: 5, vendorId: 1, warehouseId: 1, purchasePrice: 714.3, gstRate: 5, quantity: 3.0, initialQuantity: 3.0, reorderLevel: 2 },
  { id: 74, name: 'KANDA LASUN MASALA', unit: 'kg', categoryId: 5, vendorId: 1, warehouseId: 1, purchasePrice: 267.0, gstRate: 5, quantity: 2.5, initialQuantity: 2.5, reorderLevel: 2 },
  { id: 75, name: 'GODA AMASALA', unit: 'kg', categoryId: 5, vendorId: 1, warehouseId: 1, purchasePrice: 381.0, gstRate: 5, quantity: 1.0, initialQuantity: 1.0, reorderLevel: 1 },
  { id: 76, name: 'KITCHEN KING MASALA', unit: 'kg', categoryId: 5, vendorId: 1, warehouseId: 1, purchasePrice: 696.0, gstRate: 5, quantity: 5.5, initialQuantity: 5.5, reorderLevel: 2 },
  { id: 77, name: 'GREEN CURRY PASTE', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 411.0, gstRate: 12, quantity: 1.0, initialQuantity: 1.0, reorderLevel: 1 },
  { id: 78, name: 'CHAT MASALA 500 GRM', unit: 'Pkt', categoryId: 5, vendorId: 1, warehouseId: 1, purchasePrice: 590.0, gstRate: 5, quantity: 4.0, initialQuantity: 4.0, reorderLevel: 2 },
  { id: 79, name: 'WHITE PAPER POWDER', unit: 'kg', categoryId: 5, vendorId: 1, warehouseId: 1, purchasePrice: 71.0, gstRate: 5, quantity: 0.5, initialQuantity: 0.5, reorderLevel: 1 },
  { id: 80, name: 'BLACK PAPER POWDER', unit: 'kg', categoryId: 5, vendorId: 1, warehouseId: 1, purchasePrice: 76.2, gstRate: 5, quantity: 3.0, initialQuantity: 3.0, reorderLevel: 1 },
  { id: 81, name: 'OREGANO', unit: 'kg', categoryId: 5, vendorId: 1, warehouseId: 1, purchasePrice: 280.0, gstRate: 12, quantity: 2.0, initialQuantity: 2.0, reorderLevel: 0.5 },
  { id: 82, name: 'PERI PERI MASALA POWDER', unit: 'kg', categoryId: 5, vendorId: 1, warehouseId: 1, purchasePrice: 571.4, gstRate: 5, quantity: 1.2, initialQuantity: 1.2, reorderLevel: 1 },
  { id: 83, name: 'DEGHI MIRCH POWDER', unit: 'kg', categoryId: 5, vendorId: 1, warehouseId: 1, purchasePrice: 952.0, gstRate: 5, quantity: 0.9, initialQuantity: 0.9, reorderLevel: 2 },
  { id: 84, name: 'AROMETIC POWDER', unit: 'kg', categoryId: 5, vendorId: 1, warehouseId: 1, purchasePrice: 160.0, gstRate: 12, quantity: 13.0, initialQuantity: 13.0, reorderLevel: 2 },
  { id: 85, name: 'CHILLY FLEX', unit: 'kg', categoryId: 5, vendorId: 1, warehouseId: 1, purchasePrice: 161.9, gstRate: 5, quantity: 4.0, initialQuantity: 4.0, reorderLevel: 1 },
  { id: 86, name: 'EVEREST BIRYANI MASALA', unit: 'Pkt', categoryId: 5, vendorId: 1, warehouseId: 1, purchasePrice: 276.0, gstRate: 5, quantity: 0.6, initialQuantity: 0.6, reorderLevel: 2 },
  { id: 87, name: 'HING 50 GR', unit: 'Pkt', categoryId: 5, vendorId: 1, warehouseId: 1, purchasePrice: 90.0, gstRate: 5, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 5 },
  { id: 88, name: 'OIL TIN 15 LTR', unit: 'Tin', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 2142.9, gstRate: 5, quantity: 12.0, initialQuantity: 12.0, reorderLevel: 5 },
  { id: 89, name: 'COCONUT OIL', unit: 'L', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 110.0, gstRate: 5, quantity: 1.0, initialQuantity: 1.0, reorderLevel: 2 },
  { id: 90, name: 'MUSTURED OIL', unit: 'L', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 157.0, gstRate: 5, quantity: 6.0, initialQuantity: 6.0, reorderLevel: 2 },
  { id: 92, name: 'SZ PAPER CORN', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 1182.0, gstRate: 5, quantity: 0.5, initialQuantity: 0.5, reorderLevel: 1 },
  { id: 93, name: 'SALAD OIL', unit: 'L', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 266.0, gstRate: 5, quantity: 5.0, initialQuantity: 5.0, reorderLevel: 2 },
  { id: 94, name: 'GHEE', unit: 'kg', categoryId: 2, vendorId: 1, warehouseId: 1, purchasePrice: 500.0, gstRate: 12, quantity: 11.0, initialQuantity: 11.0, reorderLevel: 5 },
  { id: 95, name: 'DALDA', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 133.0, gstRate: 5, quantity: 13.0, initialQuantity: 13.0, reorderLevel: 5 },
  { id: 96, name: 'JALEPENO SLICE', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 125.4, gstRate: 12, quantity: 2.0, initialQuantity: 2.0, reorderLevel: 5 },
  { id: 97, name: 'TOMATO KETCHUP', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 80.4, gstRate: 12, quantity: 8.0, initialQuantity: 8.0, reorderLevel: 10 },
  { id: 98, name: 'TOMATO SAUCE CAN', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 232.1, gstRate: 12, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 5 },
  { id: 99, name: 'MAYONISE', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 98.0, gstRate: 12, quantity: 6.0, initialQuantity: 6.0, reorderLevel: 5 },
  { id: 100, name: 'DARK SOYA SOUCE', unit: 'L', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 40.0, gstRate: 12, quantity: 8.0, initialQuantity: 8.0, reorderLevel: 5 },
  { id: 101, name: 'RED CHILLY SOUCE', unit: 'L', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 40.0, gstRate: 12, quantity: 6.0, initialQuantity: 6.0, reorderLevel: 5 },
  { id: 102, name: 'RED CHILLY SOUCE 5 KG', unit: 'Jar', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 241.1, gstRate: 12, quantity: 3.0, initialQuantity: 3.0, reorderLevel: 2 },
  { id: 103, name: 'GREEN CHILLY SOUCE', unit: 'L', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 40.0, gstRate: 12, quantity: 33.0, initialQuantity: 33.0, reorderLevel: 10 },
  { id: 104, name: 'LIGHT SOYA SOUCE', unit: 'L', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 241.1, gstRate: 12, quantity: 2.0, initialQuantity: 2.0, reorderLevel: 2 },
  { id: 105, name: 'FUSLI PASTA', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 49.0, gstRate: 5, quantity: 12.0, initialQuantity: 12.0, reorderLevel: 10 },
  { id: 106, name: 'BBQ SOUCE', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 267.9, gstRate: 12, quantity: 4.0, initialQuantity: 4.0, reorderLevel: 2 },
  { id: 107, name: 'VINEGER', unit: 'L', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 22.0, gstRate: 12, quantity: 25.0, initialQuantity: 25.0, reorderLevel: 10 },
  { id: 108, name: 'CHOLE MASALA 500GM', unit: 'Pkt', categoryId: 5, vendorId: 1, warehouseId: 1, purchasePrice: 690.5, gstRate: 5, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 5 },
  { id: 109, name: 'KEWADA WATER', unit: 'Bottle', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 42.4, gstRate: 12, quantity: 6.0, initialQuantity: 6.0, reorderLevel: 2 },
  { id: 110, name: 'ROSE WATER', unit: 'Bottle', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 33.9, gstRate: 12, quantity: 7.0, initialQuantity: 7.0, reorderLevel: 2 },
  { id: 111, name: 'MANGO PICKEL 5 KG', unit: 'Jar', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 375.0, gstRate: 12, quantity: 1.0, initialQuantity: 1.0, reorderLevel: 1 },
  { id: 112, name: 'HONEY', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 357.1, gstRate: 5, quantity: 3.0, initialQuantity: 3.0, reorderLevel: 1 },
  { id: 113, name: 'PINEAPPLE TIN', unit: 'Tin', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 114.0, gstRate: 12, quantity: 30.0, initialQuantity: 30.0, reorderLevel: 5 },
  { id: 114, name: 'SWEET CORN TIN', unit: 'Tin', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 49.1, gstRate: 5, quantity: 6.0, initialQuantity: 6.0, reorderLevel: 10 },
  { id: 115, name: 'BABY COREN TIN', unit: 'Tin', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 90.0, gstRate: 5, quantity: 1.0, initialQuantity: 1.0, reorderLevel: 5 },
  { id: 116, name: 'CHERRY DRY', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 151.8, gstRate: 12, quantity: 7.0, initialQuantity: 7.0, reorderLevel: 1 },
  { id: 117, name: 'CHERRY TIN', unit: 'Tin', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 266.7, gstRate: 12, quantity: 1.0, initialQuantity: 1.0, reorderLevel: 2 },
  { id: 118, name: 'MANGO PULP', unit: 'Tin', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 360.0, gstRate: 12, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 5 },
  { id: 119, name: 'RED COLOR', unit: 'Bottle', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 48.3, gstRate: 18, quantity: 13.0, initialQuantity: 13.0, reorderLevel: 2 },
  { id: 120, name: 'YELLOW COLOR', unit: 'Bottle', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 48.3, gstRate: 18, quantity: 10.0, initialQuantity: 10.0, reorderLevel: 2 },
  { id: 121, name: 'GREEN COLOR', unit: 'Bottle', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 63.7, gstRate: 18, quantity: 5.0, initialQuantity: 5.0, reorderLevel: 2 },
  { id: 122, name: 'TEA POWDER SOCIETY', unit: 'kg', categoryId: 1, vendorId: 1, warehouseId: 1, purchasePrice: 523.0, gstRate: 5, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 5 },
  { id: 123, name: 'COFFE POWDER', unit: 'kg', categoryId: 1, vendorId: 1, warehouseId: 1, purchasePrice: 932.2, gstRate: 5, quantity: 4.0, initialQuantity: 4.0, reorderLevel: 1 },
  { id: 124, name: 'COCONUT MILK POWDER', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 738.0, gstRate: 5, quantity: 2.0, initialQuantity: 2.0, reorderLevel: 1 },
  { id: 125, name: 'COCONUT POWDER', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 209.5, gstRate: 5, quantity: 2.0, initialQuantity: 2.0, reorderLevel: 2 },
  { id: 126, name: 'CUSTERD POWDER', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 127.1, gstRate: 12, quantity: 3.0, initialQuantity: 3.0, reorderLevel: 1 },
  { id: 127, name: 'GULAB JAM POWDER', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 334.8, gstRate: 5, quantity: 40.0, initialQuantity: 40.0, reorderLevel: 5 },
  { id: 128, name: 'COOKING SODA', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 67.8, gstRate: 12, quantity: 2.0, initialQuantity: 2.0, reorderLevel: 1 },
  { id: 129, name: 'LIZZAT PAPAD BIG', unit: 'Pkt', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 325.0, gstRate: 0, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 5 },
  { id: 130, name: 'ENO', unit: 'Pkt', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 138.4, gstRate: 12, quantity: 4.0, initialQuantity: 4.0, reorderLevel: 10 },
  { id: 131, name: 'SAMOSA PAPAD', unit: 'Pkt', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 80.0, gstRate: 0, quantity: 10.0, initialQuantity: 10.0, reorderLevel: 5 },
  { id: 132, name: 'BOONDI', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 133.3, gstRate: 5, quantity: 5.0, initialQuantity: 5.0, reorderLevel: 5 },
  { id: 133, name: 'PAPADI', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 140.0, gstRate: 5, quantity: 32.0, initialQuantity: 32.0, reorderLevel: 5 },
  { id: 134, name: 'BREAD CRUM PANKO', unit: 'kg', categoryId: 3, vendorId: 1, warehouseId: 1, purchasePrice: 119.0, gstRate: 5, quantity: 16.0, initialQuantity: 16.0, reorderLevel: 5 },
  { id: 135, name: '0 SEV', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 142.9, gstRate: 5, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 5 },
  { id: 136, name: 'PENNEI PASTA', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 107.1, gstRate: 5, quantity: 19.0, initialQuantity: 19.0, reorderLevel: 10 },
  { id: 137, name: 'MACRONI PASTA', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 125.0, gstRate: 5, quantity: 9.0, initialQuantity: 9.0, reorderLevel: 5 },
  { id: 138, name: 'SPEGHETI PISTA', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 89.3, gstRate: 5, quantity: 4.0, initialQuantity: 4.0, reorderLevel: 5 },
  { id: 139, name: 'ALMOUND BADAM', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 758.9, gstRate: 5, quantity: 3.0, initialQuantity: 3.0, reorderLevel: 1 },
  { id: 140, name: 'TOBASCO SOUCE', unit: 'Bottle', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 205.4, gstRate: 12, quantity: 6.0, initialQuantity: 6.0, reorderLevel: 2 },
  { id: 141, name: 'PERI PERI SOUCE', unit: 'Bottle', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 160.0, gstRate: 12, quantity: 3.0, initialQuantity: 3.0, reorderLevel: 2 },
  { id: 142, name: 'OYSTER SOUCE', unit: 'Bottle', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 625.0, gstRate: 12, quantity: 1.0, initialQuantity: 1.0, reorderLevel: 1 },
  { id: 143, name: 'KASUNDI', unit: 'Bottle', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 104.1, gstRate: 12, quantity: 4.0, initialQuantity: 4.0, reorderLevel: 2 },
  { id: 144, name: 'PEANUT BUTEER', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 133.0, gstRate: 12, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 2 },
  { id: 145, name: 'RICE VINEGER', unit: 'Bottle', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 349.0, gstRate: 12, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 2 },
  { id: 146, name: 'TATA TEA AGNI', unit: 'kg', categoryId: 1, vendorId: 1, warehouseId: 1, purchasePrice: 228.6, gstRate: 5, quantity: 9.0, initialQuantity: 9.0, reorderLevel: 5 },
  { id: 147, name: 'TOMATO PUREE', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 62.5, gstRate: 12, quantity: 8.0, initialQuantity: 8.0, reorderLevel: 10 },
  { id: 148, name: 'PISTA', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 1607.1, gstRate: 5, quantity: 1.0, initialQuantity: 1.0, reorderLevel: 0.5 },
  { id: 149, name: 'GREEN OLIVES', unit: 'Jar', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 151.8, gstRate: 12, quantity: 12.0, initialQuantity: 12.0, reorderLevel: 2 },
  { id: 150, name: 'BLACK OLIVES', unit: 'Jar', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 151.8, gstRate: 12, quantity: 1.0, initialQuantity: 1.0, reorderLevel: 2 },
  { id: 151, name: 'OLIVE OIL', unit: 'L', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 380.0, gstRate: 5, quantity: 3.0, initialQuantity: 3.0, reorderLevel: 2 },
  { id: 152, name: 'DISCO PAPAD', unit: 'Pkt', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 150.0, gstRate: 0, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 5 },
  { id: 153, name: 'SWEET CHILLY SAUCE', unit: 'Bottle', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 272.3, gstRate: 12, quantity: 6.0, initialQuantity: 6.0, reorderLevel: 2 },
  { id: 154, name: 'AMB BEDGI CHILLI POWDER', unit: 'kg', categoryId: 5, vendorId: 1, warehouseId: 1, purchasePrice: 666.0, gstRate: 5, quantity: 6.0, initialQuantity: 6.0, reorderLevel: 2 },
  { id: 155, name: 'NACHOS', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 80.4, gstRate: 12, quantity: 12.0, initialQuantity: 12.0, reorderLevel: 5 },
  { id: 156, name: 'RICE NOODLES', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 285.7, gstRate: 5, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 5 },
  { id: 158, name: 'MUSHROOM TIN', unit: 'Tin', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 178.0, gstRate: 12, quantity: 2.0, initialQuantity: 2.0, reorderLevel: 5 },
  { id: 159, name: 'MILK MAID', unit: 'Tin', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 105.0, gstRate: 12, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 5 },
  { id: 160, name: 'MADRAS CURRY POWDER', unit: 'kg', categoryId: 5, vendorId: 1, warehouseId: 1, purchasePrice: 333.0, gstRate: 5, quantity: 1.0, initialQuantity: 1.0, reorderLevel: 1 },
  { id: 161, name: 'BAMBOO SHOOT', unit: 'Tin', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 107.0, gstRate: 5, quantity: 5.0, initialQuantity: 5.0, reorderLevel: 2 },
  { id: 162, name: 'CHOCO POWDER', unit: 'kg', categoryId: 3, vendorId: 1, warehouseId: 1, purchasePrice: 288.0, gstRate: 18, quantity: 5.0, initialQuantity: 5.0, reorderLevel: 1 },
  { id: 163, name: 'DARK COMPOUND', unit: 'kg', categoryId: 3, vendorId: 1, warehouseId: 1, purchasePrice: 145.0, gstRate: 18, quantity: 1.0, initialQuantity: 1.0, reorderLevel: 2 },
  { id: 164, name: 'BLACK TILL', unit: 'kg', categoryId: 5, vendorId: 1, warehouseId: 1, purchasePrice: 0.0, gstRate: 5, quantity: 4.4, initialQuantity: 4.4, reorderLevel: 1 },
  { id: 165, name: 'OIL 1LTR', unit: 'L', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 142.0, gstRate: 5, quantity: 153.0, initialQuantity: 153.0, reorderLevel: 20 },
  { id: 166, name: 'SALTED PEANUT', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 170.0, gstRate: 5, quantity: 10.0, initialQuantity: 10.0, reorderLevel: 2 },
  { id: 167, name: 'Kajun spice', unit: 'kg', categoryId: 5, vendorId: 1, warehouseId: 1, purchasePrice: 289.0, gstRate: 5, quantity: 2.0, initialQuantity: 2.0, reorderLevel: 1 },
  { id: 168, name: 'Tomyum Paste', unit: 'kg', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 495.0, gstRate: 12, quantity: 1.0, initialQuantity: 1.0, reorderLevel: 1 },
  { id: 169, name: 'CHOCOLATE SAUCE', unit: 'Bottle', categoryId: 4, vendorId: 1, warehouseId: 1, purchasePrice: 169.0, gstRate: 18, quantity: 3.0, initialQuantity: 3.0, reorderLevel: 2 },
  // New Housekeeping (HSK) Category Items
  { id: 170, name: 'cont 1000 ml dakon', unit: 'pcs', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 6.2, gstRate: 18, quantity: 50.0, initialQuantity: 50.0, reorderLevel: 10 },
  { id: 171, name: '50 ml container', unit: 'pcs', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 1.6, gstRate: 18, quantity: 150.0, initialQuantity: 150.0, reorderLevel: 20 },
  { id: 172, name: '750 ml container rect', unit: 'pcs', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 6.1, gstRate: 18, quantity: 100.0, initialQuantity: 100.0, reorderLevel: 20 },
  { id: 173, name: '1000 ml container rect', unit: 'pcs', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 6.6, gstRate: 18, quantity: 300.0, initialQuantity: 300.0, reorderLevel: 50 },
  { id: 174, name: 'attendance register', unit: 'pcs', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 90.0, gstRate: 12, quantity: 1.0, initialQuantity: 1.0, reorderLevel: 1 },
  { id: 175, name: 'paper glass 200ml', unit: 'pcs', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 0.6, gstRate: 5, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 100 },
  { id: 176, name: 'paper glass 110ml', unit: 'pcs', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 0.4, gstRate: 5, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 100 },
  { id: 177, name: 'plastic spoon', unit: 'pkt', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 28.0, gstRate: 12, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 10 },
  { id: 178, name: 'poly bag 5*8', unit: 'pkt', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 75.0, gstRate: 18, quantity: 4.0, initialQuantity: 4.0, reorderLevel: 2 },
  { id: 179, name: 'pen ut', unit: 'pcs', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 2.2, gstRate: 12, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 5 },
  { id: 180, name: 'fuel tin', unit: 'tin', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 400.0, gstRate: 18, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 2 },
  { id: 181, name: 'napkin tissue', unit: 'pkt', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 25.0, gstRate: 12, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 10 },
  { id: 182, name: 'liquid soap 35l', unit: 'can', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 22.9, gstRate: 18, quantity: 10.0, initialQuantity: 10.0, reorderLevel: 1 },
  { id: 183, name: 'garbade bag black 30*50', unit: 'pkt', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 115.0, gstRate: 12, quantity: 20.0, initialQuantity: 20.0, reorderLevel: 5 },
  { id: 184, name: 'steel scrubber', unit: 'pcs', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 20.0, gstRate: 12, quantity: 3.0, initialQuantity: 3.0, reorderLevel: 5 },
  { id: 185, name: 'green scrubber', unit: 'pcs', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 9.0, gstRate: 12, quantity: 6.0, initialQuantity: 6.0, reorderLevel: 10 },
  { id: 186, name: 'air freshner 5l can', unit: 'can', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 600.0, gstRate: 18, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 1 },
  { id: 187, name: 'floor cleaner 5ltr', unit: 'can', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 250.0, gstRate: 18, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 1 },
  { id: 188, name: 'taski r6', unit: 'can', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 730.0, gstRate: 18, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 1 },
  { id: 189, name: 'handwash 5ltr', unit: 'can', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 260.0, gstRate: 18, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 1 },
  { id: 190, name: 'cling wrap', unit: 'roll', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 310.0, gstRate: 12, quantity: 1.0, initialQuantity: 1.0, reorderLevel: 2 },
  { id: 191, name: 'silver foil', unit: 'roll', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 225.0, gstRate: 12, quantity: 2.0, initialQuantity: 2.0, reorderLevel: 2 },
  { id: 192, name: 'nirma', unit: 'kg', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 50.8, gstRate: 18, quantity: 15.0, initialQuantity: 15.0, reorderLevel: 5 },
  { id: 193, name: 'taski r1 super', unit: 'can', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 1230.0, gstRate: 18, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 1 },
  { id: 194, name: 'microfibre cloth 40*40', unit: 'pcs', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 27.0, gstRate: 12, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 5 },
  { id: 195, name: 'm fold tissue', unit: 'pkt', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 480.0, gstRate: 12, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 5 },
  { id: 196, name: 'g.b. 30*50 green', unit: 'pkt', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 125.0, gstRate: 12, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 5 },
  { id: 197, name: 'toilet brush', unit: 'pcs', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 45.0, gstRate: 12, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 2 },
  { id: 198, name: 'wet mop refill 6\'\'', unit: 'pcs', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 60.0, gstRate: 12, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 2 },
  { id: 199, name: 'double blade wiper 24\'\' set', unit: 'pcs', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 360.0, gstRate: 12, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 1 },
  { id: 200, name: '600 gms coco broom', unit: 'pcs', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 50.0, gstRate: 5, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 2 },
  { id: 201, name: 'classic broom', unit: 'pcs', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 80.0, gstRate: 5, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 2 },
  { id: 202, name: 'sponge wiper', unit: 'pcs', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 80.0, gstRate: 12, quantity: 4.0, initialQuantity: 4.0, reorderLevel: 2 },
  { id: 203, name: 'check duster medium', unit: 'pcs', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 7.5, gstRate: 12, quantity: 6.0, initialQuantity: 6.0, reorderLevel: 10 },
  { id: 204, name: 'floor duster', unit: 'pcs', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 14.0, gstRate: 12, quantity: 6.0, initialQuantity: 6.0, reorderLevel: 10 },
  { id: 205, name: 'drainage rod 7 * 1200', unit: 'pcs', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 255.0, gstRate: 18, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 1 },
  { id: 206, name: 'round bar cork screw', unit: 'pcs', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 450.0, gstRate: 18, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 1 },
  { id: 207, name: 'single bar cork screw', unit: 'pcs', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 450.0, gstRate: 18, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 1 },
  { id: 208, name: 'spade', unit: 'pcs', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 450.0, gstRate: 18, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 1 },
  { id: 209, name: 'suma grill', unit: 'can', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 1790.0, gstRate: 18, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 1 },
  { id: 210, name: 'paper bag (6.5*12*4.5) s', unit: 'pkt', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 100.0, gstRate: 5, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 5 },
  { id: 211, name: 'paper bag (8.5*13*5) l', unit: 'pkt', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 100.0, gstRate: 5, quantity: 1.0, initialQuantity: 1.0, reorderLevel: 5 },
  { id: 212, name: 'lobby dustpan set', unit: 'pcs', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 425.0, gstRate: 12, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 1 },
  { id: 213, name: 'air freshner spray', unit: 'pcs', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 100.0, gstRate: 18, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 5 },
  { id: 214, name: 'zip lock 4*6', unit: 'pkt', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 50.0, gstRate: 18, quantity: 4.0, initialQuantity: 4.0, reorderLevel: 5 },
  { id: 215, name: 'surgical gloves', unit: 'pkt', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 250.0, gstRate: 12, quantity: 1.0, initialQuantity: 1.0, reorderLevel: 2 },
  { id: 216, name: 'rubber bands 500g', unit: 'pkt', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 200.0, gstRate: 12, quantity: 0.5, initialQuantity: 0.5, reorderLevel: 1 },
  { id: 217, name: 'medimix soap 10 gms', unit: 'pcs', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 3.1, gstRate: 12, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 50 },
  { id: 218, name: 'garbage bags 19*21 black', unit: 'pkt', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 23.0, gstRate: 12, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 10 },
  { id: 219, name: 'carpet shampoo tr 101', unit: 'can', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 1450.0, gstRate: 18, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 1 },
  { id: 220, name: 'air diffuser liquid', unit: 'can', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 980.0, gstRate: 18, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 1 },
  { id: 221, name: 'cont 100 ml', unit: 'pcs', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 1.9, gstRate: 18, quantity: 50.0, initialQuantity: 50.0, reorderLevel: 100 },
  { id: 222, name: 'cont 1000 ml', unit: 'pcs', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 6.2, gstRate: 18, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 100 },
  { id: 223, name: 'cont 250 ml', unit: 'pcs', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 2.9, gstRate: 18, quantity: 200.0, initialQuantity: 200.0, reorderLevel: 100 },
  { id: 224, name: 'rect black cont 750 ml', unit: 'pcs', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 6.1, gstRate: 18, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 50 },
  { id: 225, name: 'tape 1 inch', unit: 'roll', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 12.0, gstRate: 12, quantity: 18.0, initialQuantity: 18.0, reorderLevel: 5 },
  { id: 226, name: 'butter paper roll', unit: 'roll', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 100.0, gstRate: 12, quantity: 4.0, initialQuantity: 4.0, reorderLevel: 2 },
  { id: 227, name: 'stirer wooden', unit: 'pkt', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 15.0, gstRate: 5, quantity: 11.0, initialQuantity: 11.0, reorderLevel: 5 },
  { id: 228, name: 'straw cocktail', unit: 'pkt', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 20.0, gstRate: 12, quantity: 22.0, initialQuantity: 22.0, reorderLevel: 5 },
  { id: 229, name: 'paper strow', unit: 'pkt', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 20.0, gstRate: 12, quantity: 10.0, initialQuantity: 10.0, reorderLevel: 5 },
  { id: 230, name: 'satey stick', unit: 'pkt', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 15.0, gstRate: 5, quantity: 3.0, initialQuantity: 3.0, reorderLevel: 5 },
  { id: 231, name: 'skull cap', unit: 'pcs', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 60.0, gstRate: 5, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 10 },
  { id: 232, name: 'chef cap', unit: 'pcs', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 75.0, gstRate: 5, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 10 },
  { id: 233, name: 'parcel paper bag big', unit: 'pkt', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 100.0, gstRate: 5, quantity: 1.0, initialQuantity: 1.0, reorderLevel: 5 },
  { id: 234, name: 'poly bag', unit: 'pkt', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 75.0, gstRate: 18, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 10 },
  { id: 235, name: '500ml container round', unit: 'pcs', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 4.2, gstRate: 18, quantity: 350.0, initialQuantity: 350.0, reorderLevel: 50 },
  { id: 236, name: '500ml container rect', unit: 'pcs', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 5.1, gstRate: 18, quantity: 150.0, initialQuantity: 150.0, reorderLevel: 50 },
  { id: 237, name: 'silver pouch 6*9', unit: 'pkt', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 75.0, gstRate: 12, quantity: 1.0, initialQuantity: 1.0, reorderLevel: 5 },
  { id: 238, name: 'silver pouch 6*8', unit: 'pkt', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 80.0, gstRate: 12, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 5 },
  { id: 239, name: '4q register', unit: 'pcs', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 120.0, gstRate: 12, quantity: 1.0, initialQuantity: 1.0, reorderLevel: 1 },
  { id: 240, name: 'urinal tablet', unit: 'pkt', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 35.0, gstRate: 18, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 5 },
  { id: 241, name: 'dental kit', unit: 'pcs', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 14.0, gstRate: 12, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 10 },
  { id: 242, name: 'hrt roll', unit: 'roll', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 240.0, gstRate: 12, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 5 },
  { id: 243, name: 'garnish bottel', unit: 'pcs', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 12.0, gstRate: 18, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 5 },
  { id: 244, name: 'paper chef cap', unit: 'pcs', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 5.0, gstRate: 5, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 20 },
  { id: 245, name: 'pop up tissue', unit: 'pkt', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 480.0, gstRate: 12, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 5 },
  { id: 246, name: 'rubber gloves', unit: 'pair', categoryId: 6, vendorId: 1, warehouseId: 1, purchasePrice: 65.0, gstRate: 12, quantity: 1.0, initialQuantity: 1.0, reorderLevel: 5 },
  // Vegetables (Category 7)
  { id: 247, name: 'Tomato', unit: 'kg', categoryId: 7, vendorId: 1, warehouseId: 1, purchasePrice: 46.0, gstRate: 0, quantity: 10.0, initialQuantity: 10.0, reorderLevel: 5 },
  { id: 248, name: 'Brinjal', unit: 'kg', categoryId: 7, vendorId: 1, warehouseId: 1, purchasePrice: 55.0, gstRate: 0, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 2 },
  { id: 249, name: 'Beans', unit: 'kg', categoryId: 7, vendorId: 1, warehouseId: 1, purchasePrice: 70.0, gstRate: 0, quantity: 4.0, initialQuantity: 4.0, reorderLevel: 2 },
  { id: 250, name: 'beetroot', unit: 'kg', categoryId: 7, vendorId: 1, warehouseId: 1, purchasePrice: 0.0, gstRate: 0, quantity: 0.5, initialQuantity: 0.5, reorderLevel: 1 },
  { id: 251, name: 'Cucumber', unit: 'kg', categoryId: 7, vendorId: 1, warehouseId: 1, purchasePrice: 37.0, gstRate: 0, quantity: 3.0, initialQuantity: 3.0, reorderLevel: 3 },
  { id: 252, name: 'Carrot', unit: 'kg', categoryId: 7, vendorId: 1, warehouseId: 1, purchasePrice: 36.0, gstRate: 0, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 2 },
  { id: 253, name: 'Flower', unit: 'kg', categoryId: 7, vendorId: 1, warehouseId: 1, purchasePrice: 38.0, gstRate: 0, quantity: 3.0, initialQuantity: 3.0, reorderLevel: 2 },
  { id: 254, name: 'Capsicum', unit: 'kg', categoryId: 7, vendorId: 1, warehouseId: 1, purchasePrice: 40.0, gstRate: 0, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 2 },
  { id: 255, name: 'Cabbage', unit: 'kg', categoryId: 7, vendorId: 1, warehouseId: 1, purchasePrice: 20.0, gstRate: 0, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 5 },
  { id: 256, name: 'Green Chilli', unit: 'kg', categoryId: 7, vendorId: 1, warehouseId: 1, purchasePrice: 60.0, gstRate: 0, quantity: 1.0, initialQuantity: 1.0, reorderLevel: 2 },
  { id: 257, name: 'Ginger', unit: 'kg', categoryId: 7, vendorId: 1, warehouseId: 1, purchasePrice: 60.0, gstRate: 0, quantity: 1.0, initialQuantity: 1.0, reorderLevel: 2 },
  { id: 258, name: 'Pilled Garlic', unit: 'kg', categoryId: 7, vendorId: 1, warehouseId: 1, purchasePrice: 80.0, gstRate: 0, quantity: 3.0, initialQuantity: 3.0, reorderLevel: 2 },
  { id: 259, name: 'Lemon', unit: 'kg', categoryId: 7, vendorId: 1, warehouseId: 1, purchasePrice: 40.0, gstRate: 0, quantity: 4.0, initialQuantity: 4.0, reorderLevel: 1 },
  { id: 260, name: 'Dhaniya Leave', unit: 'kg', categoryId: 7, vendorId: 1, warehouseId: 1, purchasePrice: 10.0, gstRate: 0, quantity: 3.0, initialQuantity: 3.0, reorderLevel: 1 },
  { id: 261, name: 'Mint Leave', unit: 'kg', categoryId: 7, vendorId: 1, warehouseId: 1, purchasePrice: 10.0, gstRate: 0, quantity: 6.0, initialQuantity: 6.0, reorderLevel: 1 },
  { id: 262, name: 'Palak', unit: 'kg', categoryId: 7, vendorId: 1, warehouseId: 1, purchasePrice: 13.0, gstRate: 0, quantity: 3.0, initialQuantity: 3.0, reorderLevel: 2 },
  { id: 263, name: 'Methi', unit: 'kg', categoryId: 7, vendorId: 1, warehouseId: 1, purchasePrice: 18.0, gstRate: 0, quantity: 1.0, initialQuantity: 1.0, reorderLevel: 2 },
  { id: 264, name: 'Spring Onion', unit: 'kg', categoryId: 7, vendorId: 1, warehouseId: 1, purchasePrice: 20.0, gstRate: 0, quantity: 1.0, initialQuantity: 1.0, reorderLevel: 1 },
  { id: 265, name: 'Basil', unit: 'kg', categoryId: 7, vendorId: 1, warehouseId: 1, purchasePrice: 45.0, gstRate: 0, quantity: 1.0, initialQuantity: 1.0, reorderLevel: 0.5 },
  { id: 266, name: 'Ice Berg', unit: 'kg', categoryId: 7, vendorId: 1, warehouseId: 1, purchasePrice: 100.0, gstRate: 0, quantity: 0.5, initialQuantity: 0.5, reorderLevel: 1 },
  { id: 267, name: 'Broclli', unit: 'kg', categoryId: 7, vendorId: 1, warehouseId: 1, purchasePrice: 120.0, gstRate: 0, quantity: 0.5, initialQuantity: 0.5, reorderLevel: 1 },
  { id: 268, name: 'Cherry Tomato', unit: 'kg', categoryId: 7, vendorId: 1, warehouseId: 1, purchasePrice: 120.0, gstRate: 0, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 1 },
  { id: 269, name: 'lolo rossa', unit: 'kg', categoryId: 7, vendorId: 1, warehouseId: 1, purchasePrice: 420.0, gstRate: 0, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 0.5 },
  { id: 270, name: 'Yellow Zukkini', unit: 'kg', categoryId: 7, vendorId: 1, warehouseId: 1, purchasePrice: 120.0, gstRate: 0, quantity: 1.0, initialQuantity: 1.0, reorderLevel: 1 },
  { id: 271, name: 'Green Zukkini', unit: 'kg', categoryId: 7, vendorId: 1, warehouseId: 1, purchasePrice: 120.0, gstRate: 0, quantity: 1.0, initialQuantity: 1.0, reorderLevel: 1 },
  { id: 272, name: 'Baby Corn', unit: 'kg', categoryId: 7, vendorId: 1, warehouseId: 1, purchasePrice: 95.0, gstRate: 0, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 2 },
  { id: 273, name: 'capsicum', unit: 'kg', categoryId: 7, vendorId: 1, warehouseId: 1, purchasePrice: 140.0, gstRate: 0, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 1 },
  { id: 274, name: 'Onion', unit: 'kg', categoryId: 7, vendorId: 1, warehouseId: 1, purchasePrice: 23.0, gstRate: 0, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 10 },
  { id: 275, name: 'Batata', unit: 'kg', categoryId: 7, vendorId: 1, warehouseId: 1, purchasePrice: 25.0, gstRate: 0, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 10 },
  // Seafood & Non Veg
  { id: 276, name: 'Prwans', unit: 'kg', categoryId: 8, vendorId: 1, warehouseId: 1, purchasePrice: 650.0, gstRate: 0, quantity: 6.0, initialQuantity: 6.0, reorderLevel: 2 },
  { id: 277, name: 'Surmai baby', unit: 'kg', categoryId: 8, vendorId: 1, warehouseId: 1, purchasePrice: 480.0, gstRate: 0, quantity: 1.0, initialQuantity: 1.0, reorderLevel: 1 },
  { id: 278, name: 'Basa Fish', unit: 'kg', categoryId: 8, vendorId: 1, warehouseId: 1, purchasePrice: 240.0, gstRate: 0, quantity: 8.0, initialQuantity: 8.0, reorderLevel: 2 },
  { id: 279, name: 'Mutton Chap', unit: 'kg', categoryId: 9, vendorId: 1, warehouseId: 1, purchasePrice: 840.0, gstRate: 0, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 2 },
  { id: 280, name: 'Mutton Kheema', unit: 'kg', categoryId: 9, vendorId: 1, warehouseId: 1, purchasePrice: 840.0, gstRate: 0, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 2 },
  { id: 281, name: 'Mutton Curry Cut', unit: 'kg', categoryId: 9, vendorId: 1, warehouseId: 1, purchasePrice: 800.0, gstRate: 0, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 2 },
  { id: 282, name: 'Tandoori Chicken', unit: 'kg', categoryId: 9, vendorId: 1, warehouseId: 1, purchasePrice: 230.0, gstRate: 0, quantity: 5.0, initialQuantity: 5.0, reorderLevel: 5 },
  { id: 283, name: 'Carcuss', unit: 'kg', categoryId: 9, vendorId: 1, warehouseId: 1, purchasePrice: 50.0, gstRate: 0, quantity: 5.0, initialQuantity: 5.0, reorderLevel: 10 },
  { id: 284, name: 'Leg Boneless', unit: 'kg', categoryId: 9, vendorId: 1, warehouseId: 1, purchasePrice: 315.0, gstRate: 0, quantity: 6.0, initialQuantity: 6.0, reorderLevel: 5 },
  { id: 285, name: 'Chicken Wings', unit: 'kg', categoryId: 9, vendorId: 1, warehouseId: 1, purchasePrice: 300.0, gstRate: 0, quantity: 4.0, initialQuantity: 4.0, reorderLevel: 5 },
  { id: 286, name: 'Breast Boneless', unit: 'kg', categoryId: 9, vendorId: 1, warehouseId: 1, purchasePrice: 300.0, gstRate: 0, quantity: 12.0, initialQuantity: 12.0, reorderLevel: 5 },
  { id: 287, name: 'Curry Cut', unit: 'kg', categoryId: 9, vendorId: 1, warehouseId: 1, purchasePrice: 230.0, gstRate: 0, quantity: 4.0, initialQuantity: 4.0, reorderLevel: 5 },
  { id: 288, name: 'Egg', unit: 'Tray', categoryId: 9, vendorId: 1, warehouseId: 1, purchasePrice: 180.0, gstRate: 0, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 5 },
  { id: 289, name: 'Drumsrtick', unit: 'kg', categoryId: 9, vendorId: 1, warehouseId: 1, purchasePrice: 230.0, gstRate: 0, quantity: 0.0, initialQuantity: 0.0, reorderLevel: 5 },
  { id: 290, name: 'Surmai Slice', unit: 'kg', categoryId: 8, vendorId: 1, warehouseId: 1, purchasePrice: 750.0, gstRate: 0, quantity: 1.0, initialQuantity: 1.0, reorderLevel: 1 },
  { id: 291, name: 'Pomfret', unit: 'kg', categoryId: 8, vendorId: 1, warehouseId: 1, purchasePrice: 950.0, gstRate: 0, quantity: 0.9, initialQuantity: 0.9, reorderLevel: 1 },
  // Fuel & Utilities
  { id: 292, name: 'Charcoal', unit: 'kg', categoryId: 10, vendorId: 1, warehouseId: 1, purchasePrice: 1200.0, gstRate: 18, quantity: 17.0, initialQuantity: 17.0, reorderLevel: 5 },
  { id: 293, name: 'Gas', unit: 'pcs', categoryId: 10, vendorId: 1, warehouseId: 1, purchasePrice: 1770.0, gstRate: 18, quantity: 8.0, initialQuantity: 8.0, reorderLevel: 2 },
];

export const PURCHASES: PurchaseInvoice[] = [];
export const OUTWARDS: OutwardTransaction[] = [];
export const VENDOR_PAYMENTS: VendorPayment[] = [];
export const DAILY_SALES: DailySale[] = [];
export const BANQUET_SALES: BanquetSale[] = [];

export const DEFAULT_TAX_RATES: TaxRate[] = [
  { id: 1, name: 'GST 0%', rate: 0, type: 'CGST_SGST' },
  { id: 2, name: 'GST 5%', rate: 5, type: 'CGST_SGST' },
  { id: 3, name: 'GST 12%', rate: 12, type: 'CGST_SGST' },
  { id: 4, name: 'GST 18%', rate: 18, type: 'CGST_SGST' },
  { id: 5, name: 'GST 28%', rate: 28, type: 'CGST_SGST' },
  { id: 6, name: 'IGST 18%', rate: 18, type: 'IGST' },
];

export const DEFAULT_ADDITIONAL_CHARGES: AdditionalCharge[] = [
  { id: 1, name: 'Packing Charge', type: 'FIXED', value: 20, isApplied: true },
  { id: 2, name: 'Delivery Charge', type: 'FIXED', value: 50, isApplied: true },
  { id: 3, name: 'Service Charge', type: 'PERCENTAGE', value: 5, isApplied: false },
];

export const DEFAULT_BILLING_PREFS: BillingPreferences = {
  roundOff: true,
  isInclusiveTax: false,
};